name: GHA build and deployed artifact test workflow

on:
  workflow_dispatch:
permissions:
    id-token: write
    contents: read
jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: compile and build
        run: | 
          echo "Compiling"
          sleep 30
      - name: register-build-artifact
        id: register_artifact
        uses: cloudbees-io-gha/register-build-artifact@v3
        env:
          CLOUDBEES_API_URL: "https://api.saas-preprod.beescloud.com"
        with:
          name: h-test-artifact
          url: "docker.io/hdevanan/h-test-artifact:latest"
          version: 1.0.0
          label: staging,qa,prod
          type: "docker"
          digest: "sha256:1234567890abcdef123456123456abcdefabcdef123456"
      - name: Print artifact id
        run: |
          echo '${{ steps.register_artifact.outputs.cbp_artifact_id }}'
      - name: register-deployed-artifact
        uses: HemalaDev57/register-deployed-artifact-test@master
        with: 
          artifact_id: '${{ steps.register_artifact.outputs.cbp_artifact_id }}'
          target_environment: Production
          label: staging,qa,prod
          
